spring:
  config:
    import: secret/application-secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    open-in-view: false

logging.level:
  root: info
  org.hibernate.SQL: debug
# org.hibernate.type: trace          #Spring boot 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #Spring boot 3.x, hibernate6

